<?xml version="1.0"?>
<package format="3">
  <name>navbot_description</name>
  <version>0.1.0</version>
  <description>NavBot SIH robotics simulation</description>
  <maintainer email="navbot@example.com">NavBot Team</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
</package>
