<?xml version="1.0"?>
<package format="3">
  <name>amr_bringup</name>
  <version>0.2.0</version>
  <description>Top-level launch package for the SIH26112 autonomous warehouse AMR stack.</description>
  <maintainer email="tarunkumarsahu354@gmail.com">Tarun Kumar Sahu</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>amr_mission_manager</exec_depend>
  <exec_depend>amr_navigation</exec_depend>
  <exec_depend>amr_simulation</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export><build_type>ament_cmake</build_type></export>
</package>
